/**
 * Milk-procurement cycle-roll scheduler.
 *
 * Runs daily at 04:00 IST. For every tenant with `auto_generate_cycle` enabled
 * it generates the payout cycle for the most recently closed period (pours →
 * farmer billing). Most days are a cheap no-op once the current period's cycle
 * exists.
 *
 * Idempotency lives in PayoutService.autoGenerateDueCycle: it skips when a
 * tenant-wide cycle already covers the due period, so re-firing the same day or
 * catching up after an outage is safe and self-healing.
 */

import { eq } from 'drizzle-orm';
import type { Db } from '@runq/db';
import { mpGlSettings } from '@runq/db';
import type { Redis } from 'ioredis';
import { PayoutService } from '../modules/milk-procurement/payout.service';

interface Logger {
  info(msg: string, ...args: unknown[]): void;
  warn(msg: string, ...args: unknown[]): void;
  error(msg: string, ...args: unknown[]): void;
}

const INTERVAL_MS = 60_000;
// 04:00 IST — after the leave-accrual (03:30) window to spread DB load.
const FIRE_HOUR_IST = 4;
const FIRE_MINUTE_IST = 0;

let handle: ReturnType<typeof setInterval> | null = null;
let lastFiredYmd: string | null = null;

export function startCycleRollScheduler(db: Db, _redis: Redis, logger: Logger = console): void {
  logger.info('MP cycle-roll scheduler: started (runs daily at 04:00 IST)');

  handle = setInterval(async () => {
    try {
      const ist = nowIst();
      if (ist.hour !== FIRE_HOUR_IST || ist.minute !== FIRE_MINUTE_IST) return;
      const ymd = `${ist.year}-${pad(ist.month)}-${pad(ist.date)}`;
      if (lastFiredYmd === ymd) return;
      lastFiredYmd = ymd;
      await runForAllTenants(db, ymd, logger);
    } catch (err) {
      logger.error('MP cycle-roll scheduler tick failed', err);
    }
  }, INTERVAL_MS);
}

export function stopCycleRollScheduler(): void {
  if (handle) {
    clearInterval(handle);
    handle = null;
  }
}

async function runForAllTenants(db: Db, today: string, logger: Logger): Promise<void> {
  const tenants = await db.select({ tenantId: mpGlSettings.tenantId })
    .from(mpGlSettings).where(eq(mpGlSettings.autoGenerateCycle, true));
  let generated = 0;
  for (const { tenantId } of tenants) {
    const res = await new PayoutService(db, tenantId).autoGenerateDueCycle(today);
    if (res.generated) {
      generated += 1;
      logger.info(`MP cycle-roll: tenant ${tenantId} generated ${res.count} CC cycle(s)`);
    }
  }
  logger.info(`MP cycle-roll: checked ${tenants.length} tenants, generated ${generated} cycles`);
}

interface IstParts { year: number; month: number; date: number; hour: number; minute: number; }

function nowIst(): IstParts {
  // IST is UTC+05:30, no DST.
  const d = new Date(Date.now() + 5.5 * 60 * 60 * 1000);
  return {
    year: d.getUTCFullYear(), month: d.getUTCMonth() + 1, date: d.getUTCDate(),
    hour: d.getUTCHours(), minute: d.getUTCMinutes(),
  };
}

function pad(n: number): string {
  return String(n).padStart(2, '0');
}
