// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8k75SxjPuj8ba5GajJfulp5IxQTSKMgo',
    appId: '1:1296814909:android:944df0d01b62854c5b6b54',
    messagingSenderId: '1296814909',
    projectId: 'runq-63597',
    storageBucket: 'runq-63597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyIHaZmwYmLX7C_Lvo9S659UsBUzlHs0',
    appId: '1:1296814909:ios:66d8d9dd6912e5415b6b54',
    messagingSenderId: '1296814909',
    projectId: 'runq-63597',
    storageBucket: 'runq-63597.firebasestorage.app',
    iosBundleId: 'com.quartex.runq',
  );
}
