import {
  pgTable,
  uuid,
  varchar,
  date,
  decimal,
  text,
  timestamp,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { tenants } from '../tenant';
import { users } from '../user';
import { items } from '../masters/items';
import { warehouses } from '../inventory/warehouses';
import { workOrders } from './work-orders';

/**
 * Manufacturing — WO Output rows. One row per FG batch emitted by a WO.
 *
 * `unit_cost` is zero until WO close. At close, `costing.service` rolls up
 * input cost → per-output cost and back-fills `unit_cost` + `value` here,
 * then emits a single `stock_ledger` `production_in` row whose id is stored
 * in `stock_txn_id`.
 *
 * `batch_no` is generated by the create endpoint as `<bom_code>-<YYYYMMDD>-<seq>`
 * — string identity matches the rest of inventory (see plan §4.5b).
 * `expiry_date` is required when the output item has `trackBatches=true`.
 */
export const woOutput = pgTable(
  'wo_output',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    woId: uuid('wo_id')
      .notNull()
      .references(() => workOrders.id, { onDelete: 'cascade' }),
    outputItemId: uuid('output_item_id')
      .notNull()
      .references(() => items.id),
    batchNo: varchar('batch_no', { length: 60 }).notNull(),
    warehouseId: uuid('warehouse_id')
      .notNull()
      .references(() => warehouses.id),

    qty: decimal('qty', { precision: 12, scale: 3 }).notNull(),
    uom: varchar('uom', { length: 20 }).notNull(),
    unitCost: decimal('unit_cost', { precision: 15, scale: 4 })
      .notNull()
      .default('0'),
    value: decimal('value', { precision: 15, scale: 2 }).notNull().default('0'),
    expiryDate: date('expiry_date'),

    producedAt: timestamp('produced_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    producedBy: uuid('produced_by').references(() => users.id),
    stockTxnId: uuid('stock_txn_id'),

    notes: text('notes'),
    /** Client-generated UUID (mobile offline-queue replay dedupe). NULL for
     * pre-2.5 callers; tenant-scoped partial unique index. */
    idempotencyKey: varchar('idempotency_key', { length: 64 }),
  },
  (t) => [
    uniqueIndex('uq_wo_output_batch').on(t.tenantId, t.outputItemId, t.batchNo),
    index('idx_wo_output_wo').on(t.woId),
    index('idx_wo_output_tenant').on(t.tenantId),
    index('idx_wo_output_item').on(t.outputItemId),
    index('idx_wo_output_expiry')
      .on(t.expiryDate)
      .where(sql`${t.expiryDate} IS NOT NULL`),
    uniqueIndex('uq_wo_output_idempotency')
      .on(t.tenantId, t.idempotencyKey)
      .where(sql`${t.idempotencyKey} IS NOT NULL`),
  ],
);

export type WoOutputRow = typeof woOutput.$inferSelect;
export type NewWoOutputRow = typeof woOutput.$inferInsert;
