// ─── Mock content for /help ─────────────────────────────────────────────────

const HELP_USER = {
  name: "Vaidehi",
  recipesCompleted: 7,
  recipesTotal: 14,
  badges: ["First invoice", "First reconciliation", "GST-ready"],
  streak: 4, // days
  inProgress: { recipeId: "rec_pay_vendor", stepIndex: 1 },
};

// Job-to-be-done cards on Help home.
const HELP_JOBS = [
  {
    id: "get_paid",
    title: "Get paid faster",
    description: "Send invoices, chase overdue customers, and reconcile receipts.",
    icon: "trending-up",
    accent: "emerald",
    recipes: ["rec_create_invoice", "rec_record_payment", "rec_view_aging", "rec_dunning"],
  },
  {
    id: "pay_vendors",
    title: "Pay vendors",
    description: "Enter bills, run approvals, schedule payments and TDS.",
    icon: "send",
    accent: "blue",
    recipes: ["rec_enter_bill", "rec_pay_vendor", "rec_pay_run"],
  },
  {
    id: "close_month",
    title: "Close the month",
    description: "Bank reconciliation, GST returns, and your monthly checklist.",
    icon: "check-circle-2",
    accent: "violet",
    recipes: ["rec_reconcile_bank", "rec_gst_filing", "rec_month_close"],
  },
  {
    id: "setup",
    title: "Set up runQ",
    description: "Company info, customers, vendors, and item masters.",
    icon: "settings-2",
    accent: "amber",
    recipes: ["rec_setup_company", "rec_add_customer", "rec_add_vendor"],
  },
  {
    id: "ca_handoff",
    title: "Hand off to your CA",
    description: "Tally export, audit trail, and shareable reports.",
    icon: "file-output",
    accent: "rose",
    recipes: ["rec_tally_export", "rec_audit_trail"],
  },
  {
    id: "automate",
    title: "Automate everything",
    description: "Recurring invoices, auto-reminders, and AI document inbox.",
    icon: "sparkles",
    accent: "indigo",
    recipes: ["rec_recurring", "rec_inbox_ai"],
  },
];

// Recipes — each is a numbered, step-by-step walkthrough.
const HELP_RECIPES = [
  {
    id: "rec_create_invoice",
    jobId: "get_paid",
    title: "Create your first invoice",
    summary: "Issue a tax invoice from a sales order or scratch.",
    minutes: 4,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "Open the Invoices module", body: "From the sidebar, go to **Money in → Invoices**. Click **New invoice** in the top right.", screenshot: "invoice_new" },
      { title: "Pick a customer", body: "Search by name or GSTIN. If they're new, click **+ Add new customer** inline.", screenshot: "invoice_customer" },
      { title: "Add line items", body: "Pick items from your catalog or add a custom line. GST is auto-calculated based on the place of supply.", screenshot: "invoice_lines" },
      { title: "Review tax & totals", body: "Check CGST/SGST/IGST splits at the bottom. runQ flags missing HSN codes.", screenshot: "invoice_tax" },
      { title: "Send & track", body: "Click **Save & send**. The invoice is emailed; payment status updates as receipts come in.", screenshot: "invoice_send" },
    ],
  },
  {
    id: "rec_record_payment",
    jobId: "get_paid",
    title: "Record a customer payment",
    summary: "Match a UPI/NEFT receipt to one or more invoices.",
    minutes: 3,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "Go to Receipts", body: "**Money in → Receipts → New receipt**.", screenshot: null },
      { title: "Select the customer", body: "runQ shows their open invoices, oldest first.", screenshot: null },
      { title: "Allocate the amount", body: "Spread across multiple invoices. Partial allocations are fine.", screenshot: null },
      { title: "Save", body: "Receipt is posted and invoices update automatically.", screenshot: null },
    ],
  },
  {
    id: "rec_view_aging",
    jobId: "get_paid",
    title: "Read the AR aging report",
    summary: "Understand who owes you what, by how late.",
    minutes: 5,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "Open Aging", body: "**Reports → AR Aging** or click the aging block on the dashboard.", screenshot: null },
      { title: "Read the buckets", body: "Current / 1–30 / 31–60 / 61–90 / 90+ days overdue. Click any bucket to drill in.", screenshot: null },
      { title: "Take action", body: "Send a reminder, escalate to dunning, or call the customer — all from the row.", screenshot: null },
    ],
  },
  {
    id: "rec_dunning",
    jobId: "get_paid",
    title: "Set up dunning rules",
    summary: "Auto-chase overdue customers without lifting a finger.",
    minutes: 6,
    difficulty: "Medium",
    completed: false,
    steps: [
      { title: "Open Dunning", body: "**Money in → Dunning → Rules tab**.", screenshot: null },
      { title: "Pick a template", body: "Soft / Standard / Firm. Each is a 4-touch sequence over 30 days.", screenshot: null },
      { title: "Customize timing", body: "Adjust day offsets and channel (email + SMS).", screenshot: null },
      { title: "Set guardrails", body: "Skip VIP customers, pause on dispute, escalate to owner after N days.", screenshot: null },
      { title: "Activate", body: "Toggle **Live**. Watch the Log tab to see what runQ sends.", screenshot: null },
    ],
  },
  {
    id: "rec_enter_bill",
    jobId: "pay_vendors",
    title: "Enter a vendor bill",
    summary: "Capture a bill manually or with the AI document inbox.",
    minutes: 3,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "Open Bills", body: "**Money out → Bills → New bill**. Or drop a PDF on the inbox.", screenshot: null },
      { title: "Verify AI extraction", body: "runQ pre-fills vendor, date, GSTIN, line items, GST. Spot-check and correct.", screenshot: null },
      { title: "Match to PO/GRN", body: "If linked to a PO, runQ shows a 3-way match panel. Resolve any variance.", screenshot: null },
      { title: "Send for approval", body: "Pick an approval chain. Bill moves to **Pending approval**.", screenshot: null },
    ],
  },
  {
    id: "rec_pay_vendor",
    jobId: "pay_vendors",
    title: "Pay a vendor bill",
    summary: "Schedule a payment, deduct TDS, and post the entry.",
    minutes: 4,
    difficulty: "Medium",
    completed: false,
    steps: [
      { title: "Open the bill", body: "From **Bills**, pick an approved bill that's due.", screenshot: null },
      { title: "Click Pay now", body: "Choose payment account (bank). runQ pre-selects the account with sufficient balance.", screenshot: null },
      { title: "Confirm TDS", body: "If applicable, runQ auto-deducts the right TDS section. You can override.", screenshot: null },
      { title: "Schedule or pay", body: "Pay today, or schedule for the due date. Confirm and post.", screenshot: null },
    ],
  },
  {
    id: "rec_pay_run",
    jobId: "pay_vendors",
    title: "Run a weekly pay run",
    summary: "Pay 50 vendors at once with one bank file.",
    minutes: 7,
    difficulty: "Medium",
    completed: false,
    steps: [
      { title: "New pay run", body: "**Money out → Pay runs → New run**. Pick a window (e.g., next 7 days).", screenshot: null },
      { title: "Review the queue", body: "runQ proposes bills to pay. Toggle any off if needed.", screenshot: null },
      { title: "Approve", body: "Send to approver(s). Once approved, generate the bank file.", screenshot: null },
      { title: "Upload to bank", body: "Download the NEFT/RTGS batch file and upload to your bank portal.", screenshot: null },
      { title: "Reconcile", body: "Once the bank acks, runQ marks each bill as Paid.", screenshot: null },
    ],
  },
  {
    id: "rec_reconcile_bank",
    jobId: "close_month",
    title: "Reconcile your bank statement",
    summary: "Match statement lines to invoices, bills, and journals.",
    minutes: 8,
    difficulty: "Medium",
    completed: false,
    steps: [
      { title: "Import the statement", body: "**Banking → Reconciliation**. Upload CSV/MT940, or connect via account aggregator.", screenshot: null },
      { title: "Auto-match", body: "runQ matches what it can. Confidence is shown per row.", screenshot: null },
      { title: "Resolve unmatched", body: "Match manually, split, or create a new entry. Use bulk actions for repetitive items.", screenshot: null },
      { title: "Close", body: "All matched → click **Close period**. Audit trail is locked.", screenshot: null },
    ],
  },
  {
    id: "rec_gst_filing",
    jobId: "close_month",
    title: "File GSTR-1 & GSTR-3B",
    summary: "Run readiness checks, generate, and file.",
    minutes: 10,
    difficulty: "Medium",
    completed: false,
    steps: [
      { title: "Open GST Readiness", body: "**Compliance → GST Readiness**. Pick the period.", screenshot: null },
      { title: "Resolve flags", body: "Missing HSN, invalid GSTINs, place-of-supply mismatches. Click each to fix.", screenshot: null },
      { title: "Generate GSTR-1", body: "runQ builds the JSON. Preview and download.", screenshot: null },
      { title: "File via portal", body: "Upload JSON to GSTN portal, sign with EVC/DSC.", screenshot: null },
      { title: "Generate & file 3B", body: "Same flow, with ITC reconciliation step.", screenshot: null },
    ],
  },
  {
    id: "rec_month_close",
    jobId: "close_month",
    title: "Run the month-close checklist",
    summary: "9 checks before locking the books.",
    minutes: 12,
    difficulty: "Hard",
    completed: false,
    steps: [
      { title: "Open Month Close", body: "**Books → Period close**. Pick the month.", screenshot: null },
      { title: "Run the checklist", body: "9 items: bank reconciled, AR aged, AP cleared, GST filed, etc.", screenshot: null },
      { title: "Resolve flags", body: "Each unchecked item links to where to fix it.", screenshot: null },
      { title: "Lock", body: "All green → **Lock period**. Posting is disabled below this date.", screenshot: null },
    ],
  },
  {
    id: "rec_setup_company",
    jobId: "setup",
    title: "Set up your company",
    summary: "Add your GSTIN, FY, branding, and bank accounts.",
    minutes: 5,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "Company info", body: "Name, address, PAN, GSTIN. Used on invoices.", screenshot: null },
      { title: "Financial year", body: "April–March is the default for India.", screenshot: null },
      { title: "Bank accounts", body: "Add at least one bank for receipts/payments.", screenshot: null },
      { title: "Invoice numbering", body: "Format: INV-{fy}-{seq}. Customizable.", screenshot: null },
    ],
  },
  {
    id: "rec_add_customer",
    jobId: "setup",
    title: "Add a customer",
    summary: "Capture billing details, GSTIN, and payment terms.",
    minutes: 2,
    difficulty: "Easy",
    completed: true,
    steps: [
      { title: "New customer", body: "**Money in → Customers → New customer**.", screenshot: null },
      { title: "GSTIN lookup", body: "Type the GSTIN — runQ auto-fills name and address from the GSTN portal.", screenshot: null },
      { title: "Save", body: "Customer is ready to invoice.", screenshot: null },
    ],
  },
  {
    id: "rec_add_vendor",
    jobId: "setup",
    title: "Add a vendor",
    summary: "Capture vendor PAN, GSTIN, TDS section.",
    minutes: 2,
    difficulty: "Easy",
    completed: false,
    steps: [
      { title: "New vendor", body: "**Money out → Vendors → New vendor**.", screenshot: null },
      { title: "Fill TDS info", body: "PAN + applicable TDS section (94C, 94J, 194Q…). runQ uses this on every bill.", screenshot: null },
      { title: "Save", body: "Vendor is ready.", screenshot: null },
    ],
  },
  {
    id: "rec_tally_export",
    jobId: "ca_handoff",
    title: "Export to Tally",
    summary: "Send your CA a clean .xml every month.",
    minutes: 4,
    difficulty: "Easy",
    completed: false,
    steps: [
      { title: "Open Export", body: "**Books → Export → Tally**.", screenshot: null },
      { title: "Pick the period", body: "Month, quarter, or custom range.", screenshot: null },
      { title: "Pick what to export", body: "All vouchers, masters, or both. Toggle by type.", screenshot: null },
      { title: "Download", body: "XML compatible with Tally Prime. Email or share.", screenshot: null },
    ],
  },
];

// Quick links — what users actually search for.
const HELP_QUICK_LINKS = [
  { label: "How do I issue a credit note?", icon: "file-minus" },
  { label: "Why is my GSTR-1 mismatched?", icon: "alert-triangle" },
  { label: "How does TDS auto-deduction work?", icon: "scissors" },
  { label: "Set up recurring invoices", icon: "repeat" },
  { label: "Bulk import from Tally", icon: "upload" },
  { label: "Connect my bank via account aggregator", icon: "landmark" },
];

// What's new — changelog snippets
const HELP_WHATS_NEW = [
  { date: "May 4, 2026", title: "Pay runs are 3x faster", body: "Bulk approval and parallel posting cut a 50-bill run from 4 minutes to under 90 seconds." },
  { date: "Apr 28, 2026", title: "AI document inbox", body: "Drop a PDF — runQ extracts vendor, date, GST, line items, and links to a PO." },
  { date: "Apr 22, 2026", title: "GSTR-2B reconciliation", body: "ITC mismatches surface inline on each bill, with one-click resolution." },
];

window.HELP = {
  USER: HELP_USER,
  JOBS: HELP_JOBS,
  RECIPES: HELP_RECIPES,
  QUICK_LINKS: HELP_QUICK_LINKS,
  WHATS_NEW: HELP_WHATS_NEW,
};
