/**
 * Form 24Q export builder — pure, no DB I/O.
 *
 * Produces a structured worksheet mirroring the NSDL RPU's two annexures:
 *   • Annexure I  — challan-wise deductee deduction detail (every quarter)
 *   • Annexure II — annual salary + tax computation per employee (Q4 only)
 *
 * This is the data the customer imports into / keys into NSDL's RPU; the
 * RPU + FVU then produce the final `.fvu` file uploaded to TRACES. It is
 * deliberately *not* the `.fvu` file — that format is FVU-version-specific
 * and must be generated by NSDL's own utility.
 */

import type { Form24QData } from '@runq/db';

export interface Form24QDeductor {
  tan: string;
  pan: string | null;
  name: string;
  financialYear: string;
  quarter: number;
}

function csvEsc(v: string | number | null): string {
  const s = v == null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

const MONTHS = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function buildForm24QExport(deductor: Form24QDeductor, data: Form24QData): string {
  const lines: string[] = [];

  lines.push(`# Form 24Q — TAN ${deductor.tan} · ${deductor.name}`);
  lines.push(`# FY ${deductor.financialYear} · Q${deductor.quarter}`);
  lines.push('');

  // ── Annexure I — deductee-wise deduction detail ──────────────────────
  lines.push('# Annexure I — Deductee-wise deduction detail');
  lines.push([
    'Employee Code', 'Employee Name', 'PAN', 'Payment Month',
    'Amount Paid', 'TDS Deducted',
    'Challan BSR Code', 'Challan Serial No', 'Challan Deposit Date',
  ].join(','));
  for (const r of data.annexureI) {
    lines.push([
      csvEsc(r.employeeCode),
      csvEsc(r.employeeName),
      csvEsc(r.pan),
      MONTHS[r.paymentMonth] ?? r.paymentMonth,
      r.amountPaid,
      r.tdsDeducted,
      csvEsc(r.challanBsrCode),
      csvEsc(r.challanSerialNo),
      csvEsc(r.challanDepositDate),
    ].join(','));
  }

  // ── Annexure II — annual salary detail (Q4 only) ─────────────────────
  if (data.annexureII && data.annexureII.length > 0) {
    lines.push('');
    lines.push('# Annexure II — Annual salary detail & tax computation');
    lines.push([
      'Employee Code', 'Employee Name', 'PAN', 'Months Paid',
      'Gross Salary', 'Standard Deduction', 'Taxable Income',
      'Tax on Income (incl. cess)', 'TDS Deducted',
    ].join(','));
    for (const r of data.annexureII) {
      lines.push([
        csvEsc(r.employeeCode),
        csvEsc(r.employeeName),
        csvEsc(r.pan),
        r.monthsPaid,
        r.grossSalary,
        r.standardDeduction,
        r.taxableIncome,
        r.taxOnIncome,
        r.tdsDeducted,
      ].join(','));
    }
  }

  return lines.join('\n');
}
