import type { Db } from '@runq/db';
import { ReportsService } from './reports.service';
import { getReportDateRange } from '../../utils/schedule';

interface RenderedReport {
  subject: string;
  html: string;
  text: string;
}

function formatINR(n: number): string {
  return '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function layout(companyName: string, title: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:700px;margin:0 auto;padding:20px;color:#1a1a1a;">
<div style="border-bottom:2px solid #4f46e5;padding-bottom:12px;margin-bottom:20px;">
  <h2 style="margin:0;color:#4f46e5;">${companyName}</h2>
  <p style="margin:4px 0 0;color:#666;font-size:14px;">${title}</p>
</div>
${body}
<div style="margin-top:24px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12px;color:#999;">
  Generated by runQ on ${new Date().toLocaleDateString('en-IN')}
</div>
</body></html>`;
}

function tableRow(label: string, amount: number, bold = false): string {
  const style = bold ? 'font-weight:700;border-top:2px solid #333;' : '';
  return `<tr><td style="padding:6px 12px;${style}">${label}</td><td style="padding:6px 12px;text-align:right;${style}">${formatINR(amount)}</td></tr>`;
}

function sectionHeader(title: string): string {
  return `<tr><td colspan="2" style="padding:10px 12px 4px;font-weight:600;color:#4f46e5;font-size:13px;text-transform:uppercase;letter-spacing:0.5px;">${title}</td></tr>`;
}

export class ReportRenderer {
  private svc: ReportsService;

  constructor(private db: Db, private tenantId: string, private companyName: string) {
    this.svc = new ReportsService(db, tenantId);
  }

  async render(reportType: string, frequency: string): Promise<RenderedReport> {
    switch (reportType) {
      case 'profit_and_loss': return this.renderPnL(frequency);
      case 'balance_sheet': return this.renderBalanceSheet();
      case 'cash_flow': return this.renderCashFlow(frequency);
      case 'expense_analytics': return this.renderExpenseAnalytics(frequency);
      case 'revenue_analytics': return this.renderRevenueAnalytics(frequency);
      default: throw new Error(`Unknown report type: ${reportType}`);
    }
  }

  private async renderPnL(frequency: string): Promise<RenderedReport> {
    const { from, to } = getReportDateRange(frequency);
    const data = await this.svc.getProfitAndLoss(from, to);
    const title = `Profit & Loss — ${from} to ${to}`;

    let rows = sectionHeader('Revenue');
    for (const r of data.revenue) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Total Revenue', data.totalRevenue, true);

    rows += sectionHeader('Cost of Goods Sold');
    for (const r of data.cogs) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Gross Profit', data.grossProfit, true);

    rows += sectionHeader('Operating Expenses');
    for (const r of data.operatingExpenses) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Operating Profit', data.operatingProfit, true);
    rows += tableRow('Net Profit', data.netProfit, true);

    const body = `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
    const text = `P&L (${from} to ${to}): Revenue ${formatINR(data.totalRevenue)}, Net Profit ${formatINR(data.netProfit)}`;

    return { subject: title, html: layout(this.companyName, title, body), text };
  }

  private async renderBalanceSheet(): Promise<RenderedReport> {
    const today = new Date().toISOString().slice(0, 10);
    const data = await this.svc.getBalanceSheet(today);
    const title = `Balance Sheet — as of ${today}`;

    let rows = sectionHeader('Assets');
    for (const r of data.assets) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Total Assets', data.totalAssets, true);

    rows += sectionHeader('Liabilities');
    for (const r of data.liabilities) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Total Liabilities', data.totalLiabilities, true);

    rows += sectionHeader('Equity');
    for (const r of data.equity) rows += tableRow(r.accountName, r.amount);
    rows += tableRow('Total Equity', data.totalEquity, true);

    const body = `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
    const text = `Balance Sheet (${today}): Assets ${formatINR(data.totalAssets)}, Liabilities ${formatINR(data.totalLiabilities)}, Equity ${formatINR(data.totalEquity)}`;

    return { subject: title, html: layout(this.companyName, title, body), text };
  }

  private async renderCashFlow(frequency: string): Promise<RenderedReport> {
    const { from, to } = getReportDateRange(frequency);
    const data = await this.svc.getCashFlowStatement(from, to);
    const title = `Cash Flow Statement — ${from} to ${to}`;

    let rows = '';
    rows += tableRow('Opening Cash Balance', data.openingBalance);
    rows += sectionHeader('Operating Activities');
    for (const r of data.operating) rows += tableRow(r.description, r.amount);
    rows += tableRow('Net Operating', data.netOperating, true);
    rows += sectionHeader('Investing Activities');
    for (const r of data.investing) rows += tableRow(r.description, r.amount);
    rows += tableRow('Net Investing', data.netInvesting, true);
    rows += sectionHeader('Financing Activities');
    for (const r of data.financing) rows += tableRow(r.description, r.amount);
    rows += tableRow('Net Financing', data.netFinancing, true);
    rows += tableRow('Closing Cash Balance', data.closingBalance, true);

    const body = `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
    const text = `Cash Flow (${from} to ${to}): Opening ${formatINR(data.openingBalance)}, Closing ${formatINR(data.closingBalance)}`;

    return { subject: title, html: layout(this.companyName, title, body), text };
  }

  private async renderExpenseAnalytics(frequency: string): Promise<RenderedReport> {
    const { from, to } = getReportDateRange(frequency);
    const data = await this.svc.getExpenseAnalytics(from, to);
    const title = `Expense Analytics — ${from} to ${to}`;

    let rows = sectionHeader('By Category');
    for (const c of data.byCategory) rows += tableRow(c.category, c.amount);
    rows += tableRow('Total Expenses', data.totalExpenses, true);

    if (data.topVendors.length > 0) {
      rows += sectionHeader('Top Vendors');
      for (const v of data.topVendors.slice(0, 10)) rows += tableRow(v.vendorName, v.amount);
    }

    const body = `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
    const text = `Expenses (${from} to ${to}): Total ${formatINR(data.totalExpenses)}`;

    return { subject: title, html: layout(this.companyName, title, body), text };
  }

  private async renderRevenueAnalytics(frequency: string): Promise<RenderedReport> {
    const { from, to } = getReportDateRange(frequency);
    const data = await this.svc.getRevenueAnalytics(from, to);
    const title = `Revenue Analytics — ${from} to ${to}`;

    let rows = sectionHeader('By Category');
    for (const c of data.byCategory) rows += tableRow(c.category, c.amount);
    rows += tableRow('Total Revenue', data.totalRevenue, true);

    if (data.topCustomers.length > 0) {
      rows += sectionHeader('Top Customers');
      for (const c of data.topCustomers.slice(0, 10)) rows += tableRow(c.customerName, c.amount);
    }

    const body = `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
    const text = `Revenue (${from} to ${to}): Total ${formatINR(data.totalRevenue)}`;

    return { subject: title, html: layout(this.companyName, title, body), text };
  }
}
