// 90-day cash flow forecast — bar chart with forecast distinction
function CashflowChart() {
  const months = RUNQ.CASHFLOW.months;
  const max = Math.max(...months.map((m) => Math.max(m.in, m.out)));
  const W = 600, H = 180, padL = 30, padB = 22, padT = 10, padR = 8;
  const innerW = W - padL - padR;
  const innerH = H - padB - padT;
  const groupW = innerW / months.length;
  const barW = (groupW - 6) / 2;

  return (
    <Card>
      <CardTitle
        icon="line-chart"
        title="Cash flow forecast"
        sub="Last 6 months + 3-month AI projection"
        action={
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 text-[11px] text-2"><span className="h-2 w-2 rounded-sm" style={{ background: "var(--pos)" }} />In</div>
            <div className="flex items-center gap-1.5 text-[11px] text-2"><span className="h-2 w-2 rounded-sm" style={{ background: "var(--neg)" }} />Out</div>
            <button className="text-[11px] accent-text hover:underline">Open forecast →</button>
          </div>
        }
      />
      <div className="grid grid-cols-3 gap-3 mb-4">
        <div className="rounded-md surface-2 border border-soft p-3">
          <div className="text-[10px] uppercase tracking-wider text-3">Forecast inflow (90d)</div>
          <div className="num text-[18px] font-semibold pos-text mt-0.5">{formatINR(RUNQ.CASHFLOW.forecast90.in, { short: true })}</div>
        </div>
        <div className="rounded-md surface-2 border border-soft p-3">
          <div className="text-[10px] uppercase tracking-wider text-3">Forecast outflow (90d)</div>
          <div className="num text-[18px] font-semibold neg-text mt-0.5">{formatINR(RUNQ.CASHFLOW.forecast90.out, { short: true })}</div>
        </div>
        <div className="rounded-md accent-soft-bg p-3">
          <div className="text-[10px] uppercase tracking-wider accent-text">Projected net</div>
          <div className="num text-[18px] font-semibold accent-text mt-0.5">+{formatINR(RUNQ.CASHFLOW.forecast90.net, { short: true })}</div>
        </div>
      </div>
      <div className="relative">
        <svg viewBox={`0 0 ${W} ${H}`} className="w-full h-[200px]">
          {/* grid */}
          {[0, 0.25, 0.5, 0.75, 1].map((g, i) => {
            const y = padT + innerH * (1 - g);
            return (
              <g key={i}>
                <line x1={padL} x2={W - padR} y1={y} y2={y} stroke="var(--border-soft)" strokeWidth="1" />
                <text x={padL - 4} y={y + 3} textAnchor="end" fontSize="9" fill="var(--text-3)" className="num">
                  {(max * g).toFixed(0)}L
                </text>
              </g>
            );
          })}
          {months.map((m, i) => {
            const gx = padL + i * groupW + 3;
            const inH = (m.in / max) * innerH;
            const outH = (m.out / max) * innerH;
            const y0 = padT + innerH;
            return (
              <g key={m.label}>
                <rect
                  x={gx}
                  y={y0 - inH}
                  width={barW}
                  height={inH}
                  rx="2"
                  fill="var(--pos)"
                  fillOpacity={m.forecast ? 0.45 : 0.85}
                  strokeDasharray={m.forecast ? "3 3" : ""}
                  stroke={m.forecast ? "var(--pos)" : "none"}
                />
                <rect
                  x={gx + barW + 2}
                  y={y0 - outH}
                  width={barW}
                  height={outH}
                  rx="2"
                  fill="var(--neg)"
                  fillOpacity={m.forecast ? 0.4 : 0.8}
                  strokeDasharray={m.forecast ? "3 3" : ""}
                  stroke={m.forecast ? "var(--neg)" : "none"}
                />
                <text x={gx + barW} y={H - 6} textAnchor="middle" fontSize="9.5" fill={m.forecast ? "var(--text-3)" : "var(--text-2)"} fontWeight={m.forecast ? 500 : 600}>
                  {m.label}{m.forecast ? "*" : ""}
                </text>
              </g>
            );
          })}
        </svg>
        <div className="text-[10px] text-3 mt-1 flex items-center gap-1.5">
          <Icon name="sparkles" size={10} className="accent-text" />
          <span>* Forecast generated by runQ Agent — based on recurring patterns, AR aging, and PDC schedule</span>
        </div>
      </div>
    </Card>
  );
}
window.CashflowChart = CashflowChart;
