import { useEffect, useState } from 'react';
import { RefreshCw, AlertTriangle, Info, CheckCircle2 } from 'lucide-react';
import {
  usePull2b, useReconcile2b, use2bMatches, use2bSummary,
  useRequestOtp, useVerifyOtp, useForceLogout, useBookFromMatch,
} from '@/hooks/queries/use-gst-returns';
import { useCompanySettings } from '@/hooks/queries/use-settings';
import type { Gstr2bMatch, ReconSummary, VendorCandidate, BookFromMatchPayload } from '@/hooks/queries/use-gst-returns';
import { formatINR } from '@/lib/utils';
import {
  Button, Card, CardContent, Badge, Combobox,
  Table, TableHeader, TableBody, TableRow, TableCell, Th,
  TableSkeleton, EmptyState, Modal, Input, useToast,
} from '@/components/ui';
import { PageHeader } from '@/components/ar/primitives';

function periodLabel(period: string): string {
  const month = parseInt(period.substring(0, 2), 10);
  const year = parseInt(period.substring(2), 10);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[month - 1]} ${year}`;
}

/** Generate period options, optionally filtering out months before startPeriod (MMYYYY). */
function generatePeriodOptions(startPeriod?: string): Array<{ value: string; label: string }> {
  const options: Array<{ value: string; label: string }> = [];
  const now = new Date();
  for (let i = 0; i < 12; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const yyyy = String(d.getFullYear());
    const val = `${mm}${yyyy}`;
    // Skip periods before filing start
    if (startPeriod && periodIsBefore(val, startPeriod)) continue;
    options.push({ value: val, label: periodLabel(val) });
  }
  return options;
}

function periodIsBefore(a: string, b: string): boolean {
  const aY = parseInt(a.substring(2), 10), aM = parseInt(a.substring(0, 2), 10);
  const bY = parseInt(b.substring(2), 10), bM = parseInt(b.substring(0, 2), 10);
  return aY < bY || (aY === bY && aM < bM);
}

const MONTHS_LONG = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

type PeriodGuidance = {
  status: 'too_early' | 'ready' | 'past_deadline';
  title: string;
  message: string;
};

/**
 * GSTR-2B is generated by GSTN on the 14th of M+1; GSTR-3B for period M is due on the 20th of M+1.
 * Pulling before the 14th returns empty or partial data.
 */
function getPeriodGuidance(period: string, today: Date = new Date()): PeriodGuidance | null {
  if (!period || period.length !== 6) return null;
  const m = parseInt(period.substring(0, 2), 10);
  const y = parseInt(period.substring(2), 10);
  if (!m || !y) return null;

  const generationDate = new Date(y, m, 14); // 14th of M+1 (month index m == M+1 in 0-based)
  const deadline = new Date(y, m, 20);
  const monthName = MONTHS_LONG[m - 1];
  const nextMonthName = MONTHS_LONG[m % 12];
  const fmt = (d: Date) => `${d.getDate()} ${MONTHS_LONG[d.getMonth()].slice(0, 3)} ${d.getFullYear()}`;

  if (today < generationDate) {
    return {
      status: 'too_early',
      title: `GSTR-2B for ${monthName} ${y} is not yet generated`,
      message: `GSTN generates 2B on the 14th of the following month. Available from ${fmt(generationDate)}. Pulling now will return empty or partial data.`,
    };
  }
  if (today <= deadline) {
    return {
      status: 'ready',
      title: `GSTR-2B is finalized — safe to reconcile`,
      message: `GSTR-3B for ${monthName} ${y} is due on ${fmt(deadline)}. The 2B snapshot is locked, so you have complete data to claim ITC against.`,
    };
  }
  return {
    status: 'past_deadline',
    title: `GSTR-3B deadline for ${monthName} ${y} has passed`,
    message: `The ${fmt(deadline)} deadline is over. 2B for this period remains finalized — any late supplier filings will appear in ${nextMonthName}'s 2B, not this one.`,
  };
}

const STATUS_BADGE: Record<string, { variant: 'success' | 'warning' | 'danger' | 'info'; label: string }> = {
  matched: { variant: 'success', label: 'Matched' },
  mismatched: { variant: 'warning', label: 'Mismatched' },
  not_in_books: { variant: 'danger', label: 'Not in Books' },
  not_in_2b: { variant: 'info', label: 'Not in 2B' },
};

export function ReconciliationPage() {
  const { toast } = useToast();
  const [period, setPeriod] = useState('');
  const [statusFilter, setStatusFilter] = useState<string | undefined>();

  // OTP auth state
  const { data: companyData } = useCompanySettings();
  const [showOtpModal, setShowOtpModal] = useState(false);
  const [gstUsername, setGstUsername] = useState('');
  const [otp, setOtp] = useState('');
  const [txn, setTxn] = useState('');
  const [sessionError, setSessionError] = useState<string | null>(null);

  const requestOtpMutation = useRequestOtp();
  const verifyOtpMutation = useVerifyOtp();
  const forceLogoutMutation = useForceLogout();

  const pullMutation = usePull2b();
  const reconMutation = useReconcile2b();
  const bookMutation = useBookFromMatch();
  const [bookingId, setBookingId] = useState<string | null>(null);
  // When the backend spots a near-duplicate vendor for a 2B entry, it
  // returns the candidates instead of silently creating a fresh vendor
  // (which is how we ended up with double-vendor "ELECTROTECH SYSTEMS"
  // and Padma Q/O records the first time around). The modal lets the
  // user merge into the existing vendor (auto-patching its GSTIN to the
  // 2B value) or force-create a new one.
  const [vendorDecision, setVendorDecision] = useState<
    { match: Gstr2bMatch; candidates: VendorCandidate[] } | null
  >(null);

  function runBook(payload: BookFromMatchPayload, sourceMatch: Gstr2bMatch) {
    setBookingId(sourceMatch.id);
    bookMutation.mutate(payload, {
      onSuccess: (res: any) => {
        setBookingId(null);
        const data = res?.data;
        if (data?.status === 'needs_vendor_decision') {
          setVendorDecision({ match: sourceMatch, candidates: data.candidates });
          return;
        }
        if (data?.status === 'booked') {
          setVendorDecision(null);
          toast(
            data.matchStatus === 'matched'
              ? 'Draft bill created and matched'
              : 'Draft bill created (amounts differ — review in Bills)',
            'success',
          );
        }
      },
      onError: (err: any) => {
        setBookingId(null);
        toast(err?.message ?? 'Failed to book bill', 'error');
      },
    });
  }

  const candidateReasonLabel: Record<VendorCandidate['reason'], string> = {
    same_pan: 'Same PAN — likely same legal entity',
    gstin_typo: 'GSTIN differs by one character — likely a typo',
    same_name: 'Same supplier name — GSTIN may be wrong on the existing record',
  };
  const { data: summaryData } = use2bSummary(period);
  const { data: matchesData, isLoading: matchesLoading } = use2bMatches(period, statusFilter);

  const summary: ReconSummary | null = summaryData?.data ?? null;
  const matches: Gstr2bMatch[] = matchesData?.data ?? [];
  const gstin = companyData?.data?.gstin ?? '';
  const periodOptions = generatePeriodOptions();
  const guidance = getPeriodGuidance(period);
  const blockPull = guidance?.status === 'too_early';

  // Auto-populate GST username from company settings
  useEffect(() => {
    if (companyData?.data?.gstUsername && !gstUsername) {
      setGstUsername(companyData.data.gstUsername);
    }
  }, [companyData, gstUsername]);

  function handlePullAndReconcile() {
    if (!period) { toast('Select a period', 'error'); return; }
    pullMutation.mutate(period, {
      onSuccess: () => {
        toast('GSTR-2B pulled — reconciling...', 'success');
        reconMutation.mutate(period, {
          onSuccess: () => toast('Reconciliation complete', 'success'),
          onError: (err: any) => toast(err?.message ?? 'Reconciliation failed', 'error'),
        });
      },
      onError: (err: any) => {
        const msg = err?.message ?? '';
        if (msg.includes('session expired') || msg.includes('Authenticate')) {
          setShowOtpModal(true);
          toast('GST session expired — authenticate to continue', 'error');
        } else {
          toast(msg || 'Failed to pull 2B', 'error');
        }
      },
    });
  }

  function handleRequestOtp() {
    if (!gstUsername) { toast('Enter GST portal username', 'error'); return; }
    if (!gstin) { toast('GSTIN not configured in Settings → Company', 'error'); return; }
    setSessionError(null);
    requestOtpMutation.mutate(
      { gstin, username: gstUsername },
      {
        onSuccess: (res: any) => {
          if (!res.data.success || !res.data.txn) {
            const msg = res.data.message ?? 'Failed to request OTP from GST portal';
            setSessionError(msg);
            toast(msg, 'error');
            return;
          }
          setTxn(res.data.txn);
          toast('OTP sent to your registered mobile', 'success');
        },
        onError: (err: any) => toast(err?.message ?? 'Failed to request OTP', 'error'),
      },
    );
  }

  function handleVerifyOtp() {
    if (!otp) { toast('Enter the OTP', 'error'); return; }
    verifyOtpMutation.mutate(
      { gstin, username: gstUsername, otp, txn },
      {
        onSuccess: () => {
          setShowOtpModal(false);
          setOtp('');
          setTxn('');
          toast('Authenticated — pulling 2B data...', 'success');
          // Auto-trigger pull + reconcile after auth
          if (period) handlePullAndReconcile();
        },
        onError: (err: any) => toast(err?.message ?? 'OTP verification failed', 'error'),
      },
    );
  }

  function handleForceLogout() {
    if (!gstUsername) { toast('Enter GST portal username first', 'error'); return; }
    forceLogoutMutation.mutate(
      { gstin, username: gstUsername },
      {
        onSuccess: (res: any) => {
          toast(res.data.success ? 'Session cleared. Try OTP again.' : `Logout: ${res.data.message}`, res.data.success ? 'success' : 'error');
          setSessionError(null);
          setTxn('');
        },
        onError: (err: any) => toast(err?.message ?? 'Force logout failed', 'error'),
      },
    );
  }

  const statusOptions = [
    { value: '', label: 'All' },
    { value: 'matched', label: 'Matched' },
    { value: 'mismatched', label: 'Mismatched' },
    { value: 'not_in_books', label: 'Not in Books' },
    { value: 'not_in_2b', label: 'Not in 2B' },
  ];

  return (
    <div className="max-w-6xl">
      <PageHeader
        title="GSTR-2B reconciliation"
        description="Match your purchase invoices against supplier-reported data in GSTR-2B."
      />

      {/* Period selector + actions */}
      <Card className="mb-6">
        <CardContent className="pt-4">
          <div className="flex items-end gap-4 flex-wrap">
            <div className="w-48">
              <label className="text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1 block">Period</label>
              <Combobox options={periodOptions} value={period} onChange={setPeriod} placeholder="Select month..." />
            </div>
            <Button onClick={handlePullAndReconcile} disabled={pullMutation.isPending || reconMutation.isPending || !period || blockPull}>
              <RefreshCw className={`h-4 w-4 mr-2 ${pullMutation.isPending || reconMutation.isPending ? 'animate-spin' : ''}`} />
              {pullMutation.isPending ? 'Pulling from GSTN...' : reconMutation.isPending ? 'Reconciling...' : 'Pull & Reconcile'}
            </Button>
          </div>

          {guidance && (
            <div
              className={[
                'mt-4 rounded-md border px-3 py-2.5 flex gap-2.5 text-sm',
                guidance.status === 'too_early' && 'border-amber-300 bg-amber-50 text-amber-900 dark:border-amber-800 dark:bg-amber-900/20 dark:text-amber-200',
                guidance.status === 'ready' && 'border-green-300 bg-green-50 text-green-900 dark:border-green-800 dark:bg-green-900/20 dark:text-green-200',
                guidance.status === 'past_deadline' && 'border-blue-300 bg-blue-50 text-blue-900 dark:border-blue-800 dark:bg-blue-900/20 dark:text-blue-200',
              ].filter(Boolean).join(' ')}
            >
              {guidance.status === 'too_early' && <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />}
              {guidance.status === 'ready' && <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" />}
              {guidance.status === 'past_deadline' && <Info className="h-4 w-4 mt-0.5 shrink-0" />}
              <div>
                <p className="font-medium">{guidance.title}</p>
                <p className="text-xs mt-0.5 opacity-90">{guidance.message}</p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Summary */}
      {summary && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mb-6">
          <Card className="cursor-pointer hover:ring-1 hover:ring-primary-500" onClick={() => setStatusFilter(undefined)}>
            <CardContent className="py-3">
              <p className="text-sm text-zinc-500">Total ITC Available (2B)</p>
              <p className="text-xl font-bold font-mono tabular-nums">{formatINR(summary.totalItcAvailable)}</p>
              <p className="text-xs text-zinc-400 mt-1">
                {summary.matched.count + summary.mismatched.count + summary.notInBooks.count + summary.notIn2b.count} invoices
              </p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:ring-1 hover:ring-green-500" onClick={() => setStatusFilter('matched')}>
            <CardContent className="py-3">
              <p className="text-sm text-zinc-500">ITC Claimable (Matched)</p>
              <p className="text-xl font-bold font-mono tabular-nums text-green-600">{formatINR(summary.totalItcClaimable)}</p>
              <p className="text-xs text-zinc-400 mt-1">{summary.matched.count} invoices</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:ring-1 hover:ring-red-500" onClick={() => setStatusFilter('not_in_books')}>
            <CardContent className="py-3">
              <p className="text-sm text-zinc-500">Not in Books</p>
              <p className="text-xl font-bold text-red-500">{summary.notInBooks.count} invoices</p>
              <p className="text-xs text-zinc-400 mt-1">{formatINR(summary.notInBooks.taxableValue)} taxable</p>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Filter */}
      {period && (
        <div className="flex items-center gap-3 mb-4">
          <span className="text-sm text-zinc-500">Filter:</span>
          {statusOptions.map((opt) => (
            <button
              key={opt.value}
              onClick={() => setStatusFilter(opt.value || undefined)}
              className={[
                'px-3 py-1 rounded-full text-xs font-medium transition-colors',
                (statusFilter ?? '') === opt.value
                  ? 'bg-primary-500 text-white'
                  : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200',
              ].join(' ')}
            >
              {opt.label}
            </button>
          ))}
        </div>
      )}

      {/* Matches table */}
      {!period ? (
        <EmptyState icon={RefreshCw} title="Select a Period" description="Choose a month to view reconciliation results." />
      ) : matchesLoading ? (
        <TableSkeleton />
      ) : matches.length === 0 ? (
        <EmptyState icon={RefreshCw} title="No Matches" description="Pull GSTR-2B and run reconciliation to see results." />
      ) : (
        <Card>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <Th>Status</Th>
                  <Th>Supplier</Th>
                  <Th>Invoice (2B)</Th>
                  <Th>Invoice (Books)</Th>
                  <Th className="text-right">Taxable</Th>
                  <Th className="text-right">IGST</Th>
                  <Th className="text-right">CGST</Th>
                  <Th className="text-right">SGST</Th>
                  <Th className="text-right">Total Tax</Th>
                  <Th className="text-right">Action</Th>
                </TableRow>
              </TableHeader>
              <TableBody>
                {matches.map((m) => {
                  const badge = STATUS_BADGE[m.matchStatus];
                  const igst = Number(m.igst2b);
                  const cgst = Number(m.cgst2b);
                  const sgst = Number(m.sgst2b);
                  const totalTax = igst + cgst + sgst;
                  const canBook = m.matchStatus === 'not_in_books';
                  const isBookingThis = bookMutation.isPending && bookingId === m.id;
                  return (
                    <TableRow key={m.id}>
                      <TableCell>
                        <Badge variant={badge.variant}>{badge.label}</Badge>
                      </TableCell>
                      <TableCell>
                        <p className="text-xs font-medium">{m.supplierName ?? '—'}</p>
                        <p className="text-[10px] font-mono text-zinc-400">{m.supplierGstin}</p>
                      </TableCell>
                      <TableCell className="text-xs">{m.invoiceNumber2b || '—'}</TableCell>
                      <TableCell className="text-xs">{m.invoiceNumberBooks ?? '—'}</TableCell>
                      <TableCell align="right" numeric>{formatINR(Number(m.taxableValue2b))}</TableCell>
                      <TableCell align="right" numeric className="text-zinc-500">{igst ? formatINR(igst) : '—'}</TableCell>
                      <TableCell align="right" numeric className="text-zinc-500">{cgst ? formatINR(cgst) : '—'}</TableCell>
                      <TableCell align="right" numeric className="text-zinc-500">{sgst ? formatINR(sgst) : '—'}</TableCell>
                      <TableCell align="right" numeric className="font-medium">{formatINR(totalTax)}</TableCell>
                      <TableCell align="right">
                        {canBook && (
                          <Button
                            size="sm"
                            variant="outline"
                            disabled={bookMutation.isPending}
                            onClick={() => runBook({ matchId: m.id }, m)}
                          >
                            {isBookingThis ? 'Booking…' : 'Book'}
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        </Card>
      )}

      {/* OTP Auth Modal */}
      <Modal open={showOtpModal} title="Authenticate with GST Portal" onClose={() => setShowOtpModal(false)}>
        <div className="space-y-4">
          <div>
            <label className="text-sm font-medium block mb-1">GSTIN</label>
            <Input value={gstin} disabled />
          </div>
          <div>
            <label className="text-sm font-medium block mb-1">GST Portal Username</label>
            <Input
              value={gstUsername}
              onChange={(e) => setGstUsername(e.target.value)}
              placeholder="Your GST portal username"
            />
          </div>
          {!txn ? (
            <>
              {requestOtpMutation.isPending && (
                <div className="flex items-center gap-2 text-sm text-zinc-600 dark:text-zinc-400 bg-zinc-50 dark:bg-zinc-800/50 rounded-md px-3 py-2">
                  <div className="h-4 w-4 border-2 border-primary-500 border-t-transparent rounded-full animate-spin" />
                  <span>Requesting OTP from GST portal... this may take a few seconds</span>
                </div>
              )}
              {sessionError && (
                <div className="text-sm text-red-700 dark:text-red-400 bg-red-50 dark:bg-red-900/20 rounded-md px-3 py-2 space-y-2">
                  <p><strong>GST Portal:</strong> {sessionError}</p>
                  {sessionError.toLowerCase().includes('session') && (
                    <Button
                      onClick={handleForceLogout}
                      disabled={forceLogoutMutation.isPending}
                      variant="outline"
                      className="w-full"
                    >
                      {forceLogoutMutation.isPending ? 'Clearing...' : 'Clear Stuck Session'}
                    </Button>
                  )}
                </div>
              )}
              <Button onClick={handleRequestOtp} disabled={requestOtpMutation.isPending} className="w-full">
                {requestOtpMutation.isPending ? 'Sending...' : 'Send OTP'}
              </Button>
            </>
          ) : (
            <>
              <div className="flex items-center gap-2 text-sm text-green-700 dark:text-green-400 bg-green-50 dark:bg-green-900/20 rounded-md px-3 py-2">
                <span>OTP sent to your registered mobile. Enter it below.</span>
              </div>
              <div>
                <label className="text-sm font-medium block mb-1">OTP</label>
                <Input
                  value={otp}
                  onChange={(e) => setOtp(e.target.value)}
                  placeholder="Enter 6-digit OTP"
                  maxLength={6}
                />
              </div>
              {verifyOtpMutation.isPending && (
                <div className="flex items-center gap-2 text-sm text-zinc-600 dark:text-zinc-400 bg-zinc-50 dark:bg-zinc-800/50 rounded-md px-3 py-2">
                  <div className="h-4 w-4 border-2 border-primary-500 border-t-transparent rounded-full animate-spin" />
                  <span>Verifying OTP with GSTN...</span>
                </div>
              )}
              <Button onClick={handleVerifyOtp} disabled={verifyOtpMutation.isPending} className="w-full">
                {verifyOtpMutation.isPending ? 'Verifying...' : 'Verify OTP'}
              </Button>
            </>
          )}
        </div>
      </Modal>
    </div>
  );
}
